repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black, --filter-files]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear==23.7.10]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-python-dateutil]
        args: [--ignore-missing-imports, --disallow-untyped-defs]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [javascript, typescript, css, scss, html, json, md, yaml, yml, graphql]
        exclude: 
          - '**/node_modules/.*'
          - '**/dist/.*'
          - '**/build/.*'

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.2
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - id: markdownlint
        args: [--fix, --ignore=node_modules/**, --ignore=dist/**, --ignore=build/**]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.82.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.45.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.45.0
          - eslint-config-prettier@8.8.0
          - eslint-plugin-react@7.32.2
          - eslint-plugin-react-hooks@4.6.0
          - @typescript-eslint/parser@5.62.0
          - @typescript-eslint/eslint-plugin@5.62.0
        args:
          [
            --fix,
            --max-warnings=0,
            --config=.eslintrc.cjs,
            --ext=.js,.jsx,.ts,.tsx,
          ]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.31.1
    hooks:
      - id: cspell
        args: [--config=cspell.json]
        exclude: >-
          (?x)(
            ^.*\.(jpg|jpeg|png|gif|svg|eot|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$ |
            ^.*/node_modules/.*$ |
            ^.*/dist/.*$ |
            ^.*/build/.*$ |
            ^.*\.min\.js$
          )

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [javascript, typescript, css, scss, html, json, md, yaml, yml, graphql]
        exclude: >-
          (?x)(
            ^.*/node_modules/.*$ |
            ^.*/dist/.*$ |
            ^.*/build/.*$
          )
